name: hello-world
on: push
jobs:
  react-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: discord
        uses: sebastianpopp/discord-action@releases/v2
        with: 
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: ${{ github.repository }} has been successfullly deployed.